services:
  k6:
    image: grafana/k6:0.54.0
    env_file:
      - .env
    environment:
      BASE_URL: ${BASE_URL:-https://httpbun.com}
      K6_PROMETHEUS_RW_TREND_STATS: p(90),p(95),p(99),min,max,avg
    volumes:
      - ./k6:/scripts:ro
      - ./examples:/examples:ro
    entrypoint: ["k6"]
